(function ($) {
$.Redactor.opts.langs['uk'] = {
	html: 'Код',
	video: 'Відео',
	image: 'Зображення',
	table: 'Таблиця',
	link: 'Посилання',
	link_insert: 'Вставити посилання ...',
	link_edit: 'Змінити посилання',
	unlink: 'Видалити посилання',
	formatting: 'Форматування',
	paragraph: 'Звичайний текст',
	quote: 'Цитата',
	code: 'Код',
	header1: 'Заголовок 1',
	header2: 'Заголовок 2',
	header3: 'Заголовок 3',
	header4: 'Заголовок 4',
	header5: 'Заголовок 5',
	bold:  'Напівжирний',
	italic: 'Нахилений',
	fontcolor: 'Колір тексту',
	backcolor: 'Заливка тексту',
	unorderedlist: 'Звичайний перелік',
	orderedlist: 'Нумерований перелік',
	outdent: 'Зменшити відступ',
	indent: 'Збільшити відступ',
	cancel: 'Скасувати',
	insert: 'Вставити',
	save: 'Зберегти',
	_delete: 'Видалити',
	insert_table: 'Вставити таблицю',
	insert_row_above: 'Додати рядок зверху',
	insert_row_below: 'Додати рядок знизу',
	insert_column_left: 'Додати колонку зліва',
	insert_column_right: 'Додати колонку справа',
	delete_column: 'Видалити стовпець',
	delete_row: 'Видалити рядок',
	delete_table: 'Видалити таблицю',
	rows: 'Рядки',
	columns: 'Стовпці',
	add_head: 'Додати заголовок',
	delete_head: 'Видалити заголовок',
	title: 'Підказка',
	image_position: 'Обтікання текстом',
	none: 'Ні',
	left: 'Зліва',
	right: 'Справа',
	image_web_link: 'Посилання на изображение',
	text: 'Текст',
	mailto: 'Email',
	web: 'URL',
	video_html_code: 'Код відеороліка',
	file: 'Файл',
	upload: 'Завантажити',
	download: 'Скачати',
	choose: 'Обрати',
	or_choose: 'Або оберіть',
	drop_file_here: 'Перетягніть файл сюди',
	align_left:	'За лівим краєм',
	align_center: 'За центром',
	align_right: 'За правим краєм',
	align_justify: 'Вирівняти текст за шириною',
	horizontalrule: 'Горизонтальна лінійка',
	fullscreen: 'На увесь экран',
	deleted: 'Закреслений',
	anchor: 'Якір',
	link_new_tab: 'Відкривати на новій вкладці',
	underline: 'Підкреслений',
	alignment: 'Вирівнювання',
	filename: 'Назва (необов`язково)',
	edit: 'Ред.',
	center: 'По центру',
    change_font_size: 'Змінити розмір шрифту',
    remove_font_size: 'За замовчуванням',
    change_font_family: 'Змінити шрифт',
    remove_font_family: 'За замовчуванням'
};
})( jQuery );