//wa-content/js/redactor/2
(function ($)
{
$.Redactor.opts.langs['uk'] = {
"format": "Формат",
"image": "Зображення",
"file": "Файл",
"link": "Посилання",
"bold": "Напівжирний",
"italic": "Курсив",
"deleted": "Закреслений",
"underline": "Підкреслений",
"bold-abbr": "B",
"italic-abbr": "I",
"deleted-abbr": "S",
"underline-abbr": "U",
"lists": "Списки",
"link-insert": "Вставити посилання",
"link-edit": "Редагувати посилання",
"link-in-new-tab": "Відкрити посилання у новому табі",
"unlink": "Видалити посилання",
"cancel": "Скасувати",
"close": "Закрити",
"insert": "Вставити",
"save": "Зберегти",
"delete": "Видалити",
"text": "Текст",
"edit": "Редагувати",
"general": "Загальні",
"title": "Спливаюча підказка",
"paragraph": "Звичайний текст",
"quote": "Цитата",
"code": "Код",
"heading1": "Заголовок 1",
"heading2": "Заголовок 2",
"heading3": "Заголовок 3",
"heading4": "Заголовок 4",
"heading5": "Заголовок 5",
"heading6": "Заголовок 6",
"filename": "Назва файлу",
"optional": "необов'язково",
"unorderedlist": "Ненумерований перелік",
"orderedlist": "Нумерований перелік",
"outdent": "Прибрати відступ",
"indent": "Додати відступ",
"horizontalrule": "Лінія",
"upload": "Завантажити",
"upload-label": "Перетягніть файл або ",
"accessibility-help-label": "Редактор форматованого тексту",
"caption": "Підпис",
"bulletslist": "Маркери",
"numberslist": "Нумерація",
"image-position": "Положення",
"none": "Ні",
"left": "Зліва",
"right": "Справа",
"center": "По центру",

"style": "Стиль",
"style-marked": "Виділення",
"style-code": "Моноширинний",
"style-sample": "Приклад",
"style-variable": "Зміна",
"style-shortcut": "Скорочення",
"style-cite": "Цитата",
"style-sup": "Надрядковий",
"style-sub": "Підрядковий",

"table": "Таблиця",
"insert-table": "Додати таблицю",
"insert-row-above": "Вставити рядок зверху",
"insert-row-below": "Вставити рядок знизу",
"insert-column-left": "Вставити колонку зліва",
"insert-column-right": "Вставити колонку справа",
"add-head": "Додати заголовок",
"delete-head": "Прибрати заголовок",
"delete-column": "Прибрати колонку",
"delete-row": "Прибрати рядок",
"delete-table": "Видалити таблицю",

"align": "Вирівнювання",
"align-left": "За лівим краєм",
"align-center": "По центру",
"align-right": "За правим краєм",
"align-justify": "За шириною",

"fontcolor": "Колір тексту",
"fontcolor-highlight": "Фон",
"fontcolor-text": "Текст",
"fontcolor-none": "Прибрати",

"fontfamily": "Шрифт",
"fontfamily-remove": "За замовчуванням",

"fontsize": "Розмір",
"fontsize-remove": "За замовчуванням",

"video": "Відео",
"video-html-code": "Код для вставки або посилання на Youtube или Vimeo:",
"code-to-insert": "Код для вставки:",
"blockquote-to-insert": "Цитата для вставки:"

};

})(jQuery);